[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.35"


[lint]
exclude_lints = [
  "screaming-snake-case-immutable",
  "mixed-case-variable",
  "unwrapped-modifier-logic",
  "mixed-case-function"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
